- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config', '~/.ssh', '~/.gnupg', '~/.ipython']

- link:
    ~/.agignore:
    ~/.abcde.conf:
    ~/.bashrc: bash/bashrc
    ~/.bash.d: bash/bash.d
    ~/bin: 
    ~/.dotfiles: ''
    ~/.ipython/profile_default/ipython_kernel_config.py:
    ~/.gdbinit:
    ~/.gdbinit.d:
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    ~/.gnupg/gpg.conf:
    ~/.inputrc:
    #~/.rtorrent.rc:
    ~/.profile:
    ~/.screenrc:
    ~/.ssh/config: ssh/config
    ~/.tmux.conf:
    ~/.toprc:
    ~/.vim:
    ~/.vimrc:

- shell:
  #- mkdir -p ~/.rtorrent/session ~/.rtorrent/watch ~/.rtorrent/downloads
  - git update-submodules # after linking ~/.gitconfig
