- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.agignore:
    #~/.aria2/aria2.conf:
    #~/.axelrc:
    ~/.bashrc:
    ~/.dotfiles: ''
    #~/.emacs.d:
    #~/.emacs:
    ~/.ipython/profile_default/ipython_kernel_config.py:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.gnupg/gpg.conf:
    #~/.hgrc:
    ~/.inputrc:
    #~/.rtorrent.rc:
    ~/.profile:
    ~/.screenrc:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:

- shell:
  #- mkdir -p ~/.rtorrent/session ~/.rtorrent/watch ~/.rtorrent/downloads
  - git update-submodules # after linking ~/.gitconfig
