# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# Source global definitions
if [[ -e ~/.bash.d/bashrc_default ]]
then
    . ~/.bash.d/bashrc_default
else
    . /etc/skel/.bashrc
fi


###### wtręt
# replace bash with screen instance
if [[ $TERM != "screen" && $HOSTNAME == "atl-srv-sw14" ]]
then
   echo "would be executing: exec screen -dR"
fi


# set vi-like key bindings
set -o vi

#unlimit core size
ulimit -c unlimited

shopt -s autocd     # allows `cd **/qux` to enter `./foo/bar/baz/qux`
shopt -s cdspell    # auto-correct typos in path names when using `cd`
shopt -s dotglob    # include filenames beginning with a `.` in the results of filename expansion
shopt -s globstar   # pattern `**` used in a file name expansion context will match all files and zero or more directories and subdirectories
shopt -s nocaseglob # case-insensitive globbing
shopt -s histappend # append history from the shell to the history on exit

# turn off ^S suspend feature to be able to forward-search bash history
stty -ixon

# source all separate files
for file in env aliases functions colors prompt
do
  if [[ -f ~/.bash.d/$file ]]
  then
      . ~/.bash.d/$file
  fi
done
